server:
  port: 8080
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/users
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: abcfghjkoyuimnbuiopjkrewyuiohmtyabcfghjkoyuimnbuiopjkrewyuiohmtyabcfghjkoyuimnbuiopjkrewyuiohmty
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG


